PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  base: <http://www.gov.ie/groupC/NIAH#>

SELECT  *
WHERE
  { ?heritage  base:inCounty       ?county ;
               base:inBuildingType  "Church" ;
               base:heritageName    ?heritageName
    { SELECT  ?county
      WHERE
        { SELECT  ?county (COUNT(?heritage) AS ?count) ?area
          WHERE
            { ?heritage  base:inCounty  ?county .
              ?county        base:area      ?area
            }
          GROUP BY ?county ?area
          ORDER BY DESC(?area)
          LIMIT   2
        }
      LIMIT   1
    }
  }