PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  base: <http://www.gov.ie/groupC/NIAH#>

SELECT  ?county (?e AS ?BuildingType) (( COUNT(DISTINCT ?withBuildingType) / ?area ) AS ?density)
WHERE
  { ?withBuildingType   base:inCounty         ?county.
    ?county   base:area             ?area.
    ?e   rdfs:subClassOf       base:BuildingType.
    ?withBuildingType   base:withBuildingType  ?ei.
    ?ei  rdf:type              ?e
  }
GROUP BY ?e ?county ?area
ORDER BY ?county